import { useState, useEffect } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, AlertTriangle, AlertCircle, CheckCircle2, ChevronRight, Stethoscope, Calendar, Share2, Download, Printer } from 'lucide-react';
import api from '../services/api';
import toast from 'react-hot-toast';

export default function TriageResultsPage() {
  const { assessmentId } = useParams();
  const location = useLocation();
  const navigate = useNavigate();
  const [result, setResult] = useState(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // If we have state passed from the chat, use it
    if (location.state?.result) {
      setResult(location.state.result);
      setIsLoading(false);
    } else if (assessmentId && assessmentId !== 'latest') {
      // Fetch result from backend
      const fetchAssessment = async () => {
        try {
          const response = await api.get(`/assessments/${assessmentId}`);
          const data = response.data.assessment;
          setResult({
            urgency_level: data.urgencyLevel,
            predicted_conditions: data.predictedConditions,
            specialist_recommended: data.specialistRecommended,
            recommendations: data.recommendations
          });
        } catch (error) {
          console.error("Failed to load assessment:", error);
          toast.error("Could not load assessment details");
          navigate('/history');
        } finally {
          setIsLoading(false);
        }
      };
      fetchAssessment();
    } else {
      // Mock result if not navigated directly from chat (useful for testing)
      setIsLoading(false);
      setResult({
        urgency_level: "medium",
        predicted_conditions: [
          { name: "Common Cold", confidence: 0.85 },
          { name: "Influenza (Flu)", confidence: 0.60 },
          { name: "Allergic Rhinitis", confidence: 0.35 }
        ],
        specialist_recommended: "General Physician",
        recommendations: [
          "Rest and stay hydrated.",
          "Schedule a doctor's appointment within the next 24-48 hours.",
          "Monitor your symptoms closely. Visit ER if they worsen."
        ]
      });
    }
  }, [location.state, assessmentId, navigate]);

  if (isLoading || !result) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-50">
        <div className="animate-spin w-8 h-8 border-4 border-cyan-500 border-t-transparent rounded-full"></div>
      </div>
    );
  }

  // Determine urgency styling
  const getUrgencyConfig = (level) => {
    switch(level) {
      case 'high':
        return {
          color: 'rose',
          icon: <AlertTriangle className="w-8 h-8 text-rose-500" />,
          title: 'High Urgency — Seek Immediate Care',
          bg: 'bg-rose-50',
          border: 'border-rose-200',
          textColor: 'text-rose-900'
        };
      case 'medium':
        return {
          color: 'amber',
          icon: <AlertCircle className="w-8 h-8 text-amber-500" />,
          title: 'Medium Urgency — Medical Consultation Advised',
          bg: 'bg-amber-50',
          border: 'border-amber-200',
          textColor: 'text-amber-900'
        };
      default:
        return {
          color: 'emerald',
          icon: <CheckCircle2 className="w-8 h-8 text-emerald-500" />,
          title: 'Low Urgency — Home Care Recommended',
          bg: 'bg-emerald-50',
          border: 'border-emerald-200',
          textColor: 'text-emerald-900'
        };
    }
  };

  const config = getUrgencyConfig(result.urgency_level);

  return (
    <div className="max-w-5xl mx-auto p-4 md:p-6 lg:p-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-8">
        <div>
          <button 
            onClick={() => navigate('/dashboard')}
            className="flex items-center text-sm font-medium text-slate-500 hover:text-slate-800 transition-colors mb-3"
          >
            <ArrowLeft className="w-4 h-4 mr-1" /> Back to Dashboard
          </button>
          <h1 className="text-3xl font-bold text-slate-900 tracking-tight">Assessment Results</h1>
          <p className="text-slate-500 mt-1">Generated by MediCheck AI based on your reported symptoms.</p>
        </div>
        <div className="flex gap-2">
          <button className="p-2 text-slate-600 hover:bg-slate-100 rounded-lg transition-colors" title="Print format">
            <Printer className="w-5 h-5" />
          </button>
          <button className="p-2 text-slate-600 hover:bg-slate-100 rounded-lg transition-colors" title="Download PDF">
            <Download className="w-5 h-5" />
          </button>
          <button className="p-2 text-slate-600 hover:bg-slate-100 rounded-lg transition-colors" title="Share with Doctor">
            <Share2 className="w-5 h-5" />
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Content Column */}
        <div className="lg:col-span-2 space-y-6">
          
          {/* Urgency Banner */}
          <div className={`${config.bg} border ${config.border} rounded-2xl p-6 flex flex-col sm:flex-row gap-5 items-start sm:items-center shadow-sm`}>
            <div className="shrink-0 p-3 bg-white rounded-xl shadow-sm">
              {config.icon}
            </div>
            <div>
              <h2 className={`text-xl font-bold ${config.textColor} mb-1`}>{config.title}</h2>
              <p className={`text-sm ${config.textColor} opacity-90 leading-relaxed max-w-xl`}>
                Based on the symptoms provided, we have classified your situation as <span className="font-semibold">{result.urgency_level}</span> urgency. Please review the recommendations below carefully.
              </p>
            </div>
          </div>

          {/* Predictions Card */}
          <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="px-6 py-5 border-b border-slate-100">
              <h3 className="text-lg font-bold text-slate-900">Possible Conditions</h3>
              <p className="text-sm text-slate-500">Conditions that match your symptoms</p>
            </div>
            <div className="p-0">
              <ul className="divide-y divide-slate-100">
                {result.predicted_conditions.map((condition, index) => {
                  const percentage = Math.round(condition.confidence * 100);
                  return (
                    <li key={index} className="px-6 py-5 hover:bg-slate-50 transition-colors">
                      <div className="flex justify-between items-end mb-2">
                        <span className="font-semibold text-slate-800 text-lg">{condition.name}</span>
                        <span className="text-sm font-bold text-cyan-600 bg-cyan-50 px-2 py-0.5 rounded-md border border-cyan-100">
                          {percentage}% Match
                        </span>
                      </div>
                      <div className="w-full bg-slate-100 rounded-full h-2.5 mt-3 overflow-hidden border border-slate-200/50">
                        <div 
                          className="bg-gradient-to-r from-cyan-400 to-cyan-600 h-2.5 rounded-full transition-all duration-1000 ease-out" 
                          style={{ width: `${percentage}%` }}
                        ></div>
                      </div>
                    </li>
                  )
                })}
              </ul>
            </div>
          </div>

          {/* Recommendations Card */}
          <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
            <div className="flex items-center gap-3 mb-5">
              <div className="p-2 bg-cyan-50 text-cyan-600 rounded-lg">
                <Stethoscope className="w-5 h-5" />
              </div>
              <h3 className="text-lg font-bold text-slate-900">Recommended Next Steps</h3>
            </div>
            <ul className="space-y-4">
              {result.recommendations.map((rec, index) => (
                <li key={index} className="flex gap-4">
                  <div className="w-6 h-6 rounded-full bg-slate-100 flex items-center justify-center shrink-0 mt-0.5 border border-slate-200">
                    <span className="text-xs font-bold text-slate-500">{index + 1}</span>
                  </div>
                  <span className="text-slate-700 leading-relaxed">{rec}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Sidebar Column */}
        <div className="space-y-6">
          {/* Action Card */}
          <div className="bg-slate-900 rounded-2xl shadow-lg p-6 text-white border border-slate-800 relative overflow-hidden group">
            {/* Background design elements */}
            <div className="absolute top-0 right-0 p-8 opacity-10 pointer-events-none group-hover:scale-110 transition-transform duration-700">
              <Calendar className="w-24 h-24" />
            </div>
            
            <h3 className="text-xl font-bold mb-2">Need to see a doctor?</h3>
            <p className="text-slate-300 text-sm mb-6 leading-relaxed">
              Based on your results, we recommend consulting a <span className="text-white font-semibold">{result.specialist_recommended || "General Physician"}</span>.
            </p>
            
            <button 
              onClick={() => navigate(`/book-appointment/${assessmentId || 'new'}`)}
              className="w-full py-3.5 px-4 bg-cyan-500 hover:bg-cyan-400 text-slate-900 font-bold rounded-xl transition-all shadow-md hover:shadow-cyan-500/25 flex justify-between items-center group/btn"
            >
              Book Appointment
              <ChevronRight className="w-5 h-5 group-hover/btn:translate-x-1 transition-transform" />
            </button>
          </div>

          {/* Speciality Highlight */}
          <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-5">
            <h4 className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-4">Recommended Specialist</h4>
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 bg-indigo-50 border border-indigo-100 rounded-xl flex items-center justify-center text-indigo-600">
                <Stethoscope className="w-6 h-6" />
              </div>
              <div>
                <p className="font-bold text-slate-900 text-lg">{result.specialist_recommended || "General Physician"}</p>
                <p className="text-xs text-slate-500 line-clamp-1">Available at 12 nearby clinics</p>
              </div>
            </div>
          </div>

          {/* Disclaimer */}
          <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 text-xs text-slate-500 leading-relaxed">
            <span className="font-bold text-slate-700">Disclaimer:</span> This is an AI-generated assessment for informational purposes only. It is not a medical diagnosis. Always consult with a qualified healthcare provider for proper diagnosis and treatment. In case of emergency, call your local emergency hotline immediately.
          </div>
        </div>

      </div>
    </div>
  );
}
